//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using SqlProviderServices = System.Data.Entity.SqlServer.SqlProviderServices;
namespace Repositorios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PW3_EA2Entities : DbContext
    {
        public PW3_EA2Entities()
            : base("name=PW3_EA2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GolesPorJugadorEquipo> GolesPorJugadorEquipoes { get; set; }
        public virtual DbSet<Jugador> Jugadors { get; set; }
    }
}
